#!/usr/bin/bash

mysql() {
    clear
    printf "\t%s[[ %sSetting up MySQL%s ]]\n%s" "$(tput setaf 3)" "$(tput sgr0)" "$(tput setaf 3)" "$(tput sgr0)"

    if [ ! $(command -v mariadb) ]; then
        sudo pacman -S mariadb
    fi

    sudo mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql

    sudo systemctl enable mariadb.service
    sudo systemctl start mariadb.service
    sudo mysql_secure_installation

    cat <<- _EOF_
            MariaDB [(none)]:- CREATE USER 'username'@'localhost' IDENTIFIED BY 'some_pass';
                On 'username' --- "write your username"
                On 'some_pass' --- "write your password"
            MariaDB [(none)]:- GRANT ALL PRIVILEGES ON *.* TO 'username'@'localhost';
_EOF_

    sudo mysql -u root -p
    flush privileges;
    quit

	printf "\n\n%s%s[✔] D O N E %s\n" "$(tput bold)" "$(tput setaf 2)" "$(tput sgr0)"
}

gitssh() {
    clear
    printf "\t%s[[ %sSetting up SSH%s ]]\n\n%s" "$(tput setaf 3)" "$(tput sgr0)" "$(tput setaf 3)" "$(tput sgr0)"

    echo -n "Enter your email: "
    read -r EMAIL

    echo -n "Enter your username: "
    read -r NAME

    if [[ -z $EMAIL || -z $NAME ]]; then
        echo
        echo "[ERR] Please provide github email and username!"
        exit 1
    fi

    echo -n "Enter hostname (github.com): "
    read -r HOST
    HOST="${HOST:-github.com}"

    KEY_DIR="$HOME/.ssh/keys/$HOST"
    KEY_FILE="$KEY_DIR/$NAME"

    mkdir -p "$KEY_DIR"

    ssh-keygen -q -f "$KEY_FILE" -N "" -t ed25519 -C "$EMAIL"

    echo
    echo "------------------------------"
    echo
    echo "1. Copy the following public key and paste into $HOST ssh dashboard"
    echo
    command cat "$KEY_FILE.pub"
    echo
    echo "2. Paste the following into ~/.ssh/config"
    echo "
    Host $NAME
        Hostname $HOST
        IdentityFile $KEY_FILE
    "
    echo
    echo "3. Run the following command to clone any repository"
    echo
    echo "git clone git@$NAME:<org>/<repo>"
}

lightdm() {
    cd $HOME
    # If you prefer the last stable release, download from the releases page instead: https://github.com/NoiSek/Aether/releases/latest
    git clone git@github.com:NoiSek/Aether.git
    sudo cp --recursive Aether /usr/share/lightdm-webkit/themes/Aether

    # Set default lightdm-webkit2-greeter theme to Aether
    sudo sed -i 's/^webkit_theme\s*=\s*\(.*\)/webkit_theme = lightdm-webkit-theme-aether #\1/g' /etc/lightdm/lightdm-webkit2-greeter.conf

    # Set default lightdm greeter to lightdm-webkit2-greeter
    sudo sed -i 's/^\(#?greeter\)-session\s*=\s*\(.*\)/greeter-session = lightdm-webkit2-greeter #\1/ #\2g' /etc/lightdm/lightdm.conf

    rm -rf $HOME/Aether
}

firefoxx() {
    if $(pacman -Qi "firefox" &>/dev/null); then
		if [ ! -d "$HOME/.mozilla/firefox" ]; then
			sudo su ${USER} -s /bin/zsh -lc "timeout 2s firefox --headless"
		fi

		for archive in $(command ls ~/dotfiles/misc/firefox/); do
			if [ -e "$HOME/.mozilla/firefox/*.default-release/$archive" ]; then
				mv "$HOME/.mozilla/firefox/*.default-release/$archive" "$backup_folder/$archive_$date"
				if [ $? -eq 0 ]; then
					printf "%s✓ $archive backed up successfully at $backup_folder/config/${archive}_$date%s\n" "$(tput setaf 2)" "$(tput sgr0)"
				else
					printf "%s%s✗ %s failed to be backed up, you must copy it manually%s\n" "$(tput bold)" "$(tput setaf 1)" "${archive}" "$(tput sgr0)"
				fi
			else
				printf "%s✗ $archive does not exist in $HOME/.mozilla/firefox/%s\n" "$(tput setaf 1)" "$(tput sgr0)"
			fi
			sleep 1
		done

		for archive in $(command ls ~/dotfiles/misc/firefox/); do
			ln -s "$HOME/dotfiles/misc/firefox/$archive" ~/.mozilla/firefox/*.default-release/$archive
			if [ $? -eq 0 ]; then
				printf "%s%s✓ $archive linked!!%s\n" "$(tput bold)" "$(tput setaf 2)" "$(tput sgr0)"
			else
				printf "%s✗ $archive is not linked!!%s\n" "$(tput setaf 1)" "$(tput sgr0)"				
			fi
			sleep 1
		done
	else
		printf "%s✗ Firefox is not instaleed on the system%s\n" "$(tput setaf 1)" "$(tput sgr0)"
		sleep 2
	fi
}

if [ $# -gt 0 ]; then
    case "$1" in
    -f | --firefox)
        firefoxx
        ;;
    -s | --ssh)
        gitssh
        ;;
    ?)
        exit 1
        ;;
    esac
fi
