#!/usr/bin/env bash
#  ╦═╗╔═╗╔╗╔╔╦╗╔═╗╔╦╗  ╦ ╦╔═╗╦  ╦
#  ╠╦╝╠═╣║║║ ║║║ ║║║║  ║║║╠═╣║  ║
#  ╩╚═╩ ╩╝╚╝═╩╝╚═╝╩ ╩  ╚╩╝╩ ╩╩═╝╩═╝
#	Simple script to set random wallpaper using FEH
#   Author: z0mbi3
#	url: https://github.com/gh0stzk

if [ $CUSTOM_WALL = "Yes" ]; then
    if [ -d "$HOME/.config/wall" ]; then
        feh --randomize --no-fehbg --bg-fill $HOME/.config/wall/
    else
        # Clone it to the perfect location
        echo "Cloning adityastomar67's Walls..."
        git clone --quiet https://github.com/adityastomar67/Wallpapers "$HOME/.config/wall"

        # Move all the static wallpapers to `wall` directory and select the files with .png extension
        cd "$HOME/.config/wall" || exit
        command mv Static/* .
        /usr/bin/ls | grep "wall[0-9]*.png" >list.txt

        # Move all the .png files to .jpg
        list="./list.txt"
        while IFS= read -r file; do
            mv -- "$file" "${file%.png}.jpg"
        done <"$list"

        # Remove unnecessary files and set wallpaper
        command rm -rf .git/ README.md Static Live list.txt
    fi
else
    feh --randomize --no-fehbg --bg-fill $HOME/.config/bspwm/rices/$RICETHEME/walls/
fi
exit 0
