#!/usr/bin/env bash
#  ╦═╗╔═╗╔╗╔╔╦╗╔═╗╔╦╗  ╦ ╦╔═╗╦  ╦
#  ╠╦╝╠═╣║║║ ║║║ ║║║║  ║║║╠═╣║  ║
#  ╩╚═╩ ╩╝╚╝═╩╝╚═╝╩ ╩  ╚╩╝╩ ╩╩═╝╩═╝
#	Simple script to set random wallpaper using FEH
#   Author: z0mbi3
#	url: https://github.com/gh0stzk

if [ "$CUSTOM_WALL" = "Yes" ]; then
    feh --randomize --no-fehbg --bg-fill $HOME/.config/wall/
else
    feh --randomize --no-fehbg --bg-fill $HOME/.config/bspwm/rices/$RICETHEME/walls/
fi

exit 0
