#!/usr/bin/env bash
#  ╦═╗╦╔═╗╔═╗  ╔═╗╔═╗╦  ╔═╗╔═╗╔╦╗╔═╗╦═╗  - z0mbi3
#  ╠╦╝║║  ║╣   ╚═╗║╣ ║  ║╣ ║   ║ ║ ║╠╦╝  - https://github.com/gh0stzk/dotfiles
#  ╩╚═╩╚═╝╚═╝  ╚═╝╚═╝╩═╝╚═╝╚═╝ ╩ ╚═╝╩╚═  - z0mbi3.zk@protonmail.com

cfg_file="$HOME/.config/bspwm/rice.cfg"
rofi_command="rofi -theme $HOME/.config/bspwm/scripts/RiceSelector.rasi"

# Options
emilia="󰔿 Emilia"
jan="󰔿 Jan"
aline="󰔿 Aline"
isabel="󰔿 Isabel"
andrea="󰔿 Andrea"
cynthia="󰔿 Cynthia"
silvia="󰔿 Silvia"
melissa="󰔿 Melissa"
pamela="󰔿 Pamela"
cristina="󰔿 Cristina"
karla="󰔿 Karla"
z0mbi3="󰔿 z0mbi3"

options="$emilia\n$jan\n$aline\n$isabel\n$andrea\n$cynthia\n$silvia\n$melissa\n$pamela\n$cristina\n$karla\n$z0mbi3"
chosen="$(printf "$options" | $rofi_command -dmenu)"
case $chosen in

	$emilia)
		cat <<< "emilia" > ${cfg_file}
		bspc wm -r
        xrdb merge "$HOME/.config/bspwm/rices/$RICETHEME/xresources" && kill -USR1 $(pidof st)
		;;
	$jan)
		cat <<< "jan" > ${cfg_file}
		bspc wm -r
        xrdb merge "$HOME/.config/bspwm/rices/$RICETHEME/xresources" && kill -USR1 $(pidof st)
		;;
	$aline)
		cat <<< "aline" > ${cfg_file}
		bspc wm -r
        xrdb merge "$HOME/.config/bspwm/rices/$RICETHEME/xresources" && kill -USR1 $(pidof st)
		;;
	$isabel)
		cat <<< "isabel" > ${cfg_file}
		bspc wm -r
        xrdb merge "$HOME/.config/bspwm/rices/$RICETHEME/xresources" && kill -USR1 $(pidof st)
		;;
	$andrea)
		cat <<< "andrea" > ${cfg_file}
		bspc wm -r
        xrdb merge "$HOME/.config/bspwm/rices/$RICETHEME/xresources" && kill -USR1 $(pidof st)
		;;
	$cynthia)
		cat <<< "cynthia" > ${cfg_file}
		bspc wm -r
        xrdb merge "$HOME/.config/bspwm/rices/$RICETHEME/xresources" && kill -USR1 $(pidof st)
		;;
	$silvia)
		cat <<< "silvia" > ${cfg_file}
		bspc wm -r
        xrdb merge "$HOME/.config/bspwm/rices/$RICETHEME/xresources" && kill -USR1 $(pidof st)
		;;
	$melissa)
		cat <<< "melissa" > ${cfg_file}
		bspc wm -r
        xrdb merge "$HOME/.config/bspwm/rices/$RICETHEME/xresources" && kill -USR1 $(pidof st)
		;;
	$pamela)
		cat <<< "pamela" > ${cfg_file}
		bspc wm -r
        xrdb merge "$HOME/.config/bspwm/rices/$RICETHEME/xresources" && kill -USR1 $(pidof st)
		;;
	$cristina)
		cat <<< "cristina" > ${cfg_file}
		bspc wm -r
        xrdb merge "$HOME/.config/bspwm/rices/$RICETHEME/xresources" && kill -USR1 $(pidof st)
		;;
	$karla)
		cat <<< "karla" > ${cfg_file}
		bspc wm -r
        xrdb merge "$HOME/.config/bspwm/rices/$RICETHEME/xresources" && kill -USR1 $(pidof st)
		;;
	$z0mbi3)
		cat <<< "z0mbi3" > ${cfg_file}
		bspc wm -r
        xrdb merge "$HOME/.config/bspwm/rices/$RICETHEME/xresources" && kill -USR1 $(pidof st)
		;;
esac