#!/usr/bin/env bash
#  ╔╦╗╔═╗╦═╗╔╦╗
#   ║ ║╣ ╠╦╝║║║
#   ╩ ╚═╝╩╚═╩ ╩
#	Script to open with selected terminal
#   Author: z0mbi3
#	url: https://github.com/gh0stzk

[ -f $HOME/.local/bin/alacritty ] && TERM=$HOME/.local/bin/alacritty || TERM=alacritty

case "$1" in
  --ot)
    $(TERM);;
  --oft)
    $(TERM --class FloaTerm,Alacritty);;
  --ou)
    $(TERM --hold --class Updating,Alacritty -e yay -Syyu --devel);;
  --ocu)
	  $(TERM --hold --class Updating,Alacritty -e checkupdates);;
  --or)
    $(TERM --class Ranger,Alacritty -e ranger);;
  --ov)
    $(TERM -e nvim);;
  --om)
    $(TERM --class MusicPlayer,Alacritty -e ncmpcpp);;
  --of)
    $(TERM --hold --class Sysfetch,Alacritty -e ~/.local/bin/sysfetch    );;
  *)
    echo "Not a valid option!!";;
esac
